name: .NET

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Restore slnx
      run: dotnet restore

    - name: Build slnx
      run: dotnet build --no-restore -c Release

    - name: Test slnx
      run: dotnet test --no-restore -c Release

    - name: Pack slnx
      run: dotnet pack --no-build -o ~/nuget -c Release

    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: >
        dotnet nuget push ~/nuget/*.nupkg
        -s https://api.nuget.org/v3/index.json
        -k ${{ secrets.NUGET_SECRET }}
        --skip-duplicate