name: .NET

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

     # Add NuGet Sources

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Add GarageGroup NuGet Source
      run: >
        dotnet nuget add source ${{ vars.GG_NUGET_SOURCE_URL }}
        -n garage
        -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
        -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --store-password-in-clear-text

    # Handler.FailureCode

    - name: Restore Handler.FailureCode
      run: dotnet restore ./src/*/Handler.FailureCode.csproj

    - name: Build Handler.FailureCode
      run: dotnet build ./src/*/Handler.FailureCode.csproj --no-restore  -c Release

    - name: Pack Handler.FailureCode
      run: dotnet pack ./src/*/Handler.FailureCode.csproj --no-restore -o ~/nuget  -c Release

    # Handler.Core

    - name: Restore Handler.Core
      run: dotnet restore ./src/*/Handler.Core.csproj

    - name: Build Handler.Core
      run: dotnet build ./src/*/Handler.Core.csproj --no-restore  -c Release

    - name: Pack Handler.Core
      run: dotnet pack ./src/*/Handler.Core.csproj --no-restore -o ~/nuget  -c Release

    # Handler.Union

    - name: Restore Handler.Union
      run: dotnet restore ./src/*/Handler.Union.csproj

    - name: Build Handler.Union
      run: dotnet build ./src/*/Handler.Union.csproj --no-restore  -c Release

    - name: Pack Handler.Union
      run: dotnet pack ./src/*/Handler.Union.csproj --no-restore -o ~/nuget  -c Release

    # Handler.Console

    - name: Restore Handler.Console
      run: dotnet restore ./src/*/Handler.Console.csproj

    - name: Build Handler.Console
      run: dotnet build ./src/*/Handler.Console.csproj --no-restore  -c Release

    - name: Pack Handler.Console
      run: dotnet pack ./src/*/Handler.Console.csproj --no-restore -o ~/nuget  -c Release

    # Handler.AspNetCore.Generator

    - name: Restore Handler.AspNetCore.Generator
      run: dotnet restore ./src/*/Handler.AspNetCore.Generator.csproj

    - name: Build Handler.AspNetCore.Generator
      run: dotnet build ./src/*/Handler.AspNetCore.Generator.csproj --no-restore  -c Release

    - name: Pack Handler.AspNetCore.Generator
      run: dotnet pack ./src/*/Handler.AspNetCore.Generator.csproj --no-restore -o ~/nuget  -c Release

    # Handler.AspNetCore

    - name: Restore Handler.AspNetCore
      run: dotnet restore ./src/*/Handler.AspNetCore.csproj

    - name: Build Handler.AspNetCore
      run: dotnet build ./src/*/Handler.AspNetCore.csproj --no-restore  -c Release

    - name: Pack Handler.AspNetCore
      run: dotnet pack ./src/*/Handler.AspNetCore.csproj --no-restore -o ~/nuget  -c Release

    # Push

    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: >
        dotnet nuget push "../../../nuget/*.nupkg"
        -s ${{ vars.GG_NUGET_SOURCE_URL }}
        -k ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --skip-duplicate